name: CD Build Multiarch OpenSSL+Quic BuildEnv Docker Image

on:
  workflow_run:
    workflows: ["cd-build-openssl-buildenv"]
    types:
      - completed
  workflow_dispatch:

env:
  DOCKERHUB_SLUG: "madnuttah/openssl-buildenv"

jobs:

  detect_versions:
    runs-on: ubuntu-latest
    outputs:
      OPENSSL_VERSION: ${{ steps.detect.outputs.OPENSSL_VERSION }}
      OPENSSL_BUILDENV_VERSION: ${{ steps.detect.outputs.OPENSSL_BUILDENV_VERSION }}
      OPENSSL_SHA256: ${{ steps.detect.outputs.OPENSSL_SHA256 }}
      NGTCP2_VERSION: ${{ steps.detect.outputs.NGTCP2_VERSION }}
      NGHTTP3_VERSION: ${{ steps.detect.outputs.NGHTTP3_VERSION }}
      SFPARSE_VERSION: ${{ steps.detect.outputs.SFPARSE_VERSION }}
      QUIC_BUILDENV_VERSION: ${{ steps.detect.outputs.QUIC_BUILDENV_VERSION }}
      QUIC_BUILDENV_BUILD_DATE: ${{ steps.detect.outputs.QUIC_BUILDENV_BUILD_DATE }}

    steps:
      - name: Fetch buildvars
        id: detect
        run: |
          curl -s -L https://raw.githubusercontent.com/madnuttah/openssl-buildenv/main/buildvars -o buildvars
          source buildvars
          echo "OPENSSL_VERSION=$OPENSSL_VERSION" >> $GITHUB_OUTPUT
          echo "OPENSSL_BUILDENV_VERSION=$OPENSSL_BUILDENV_VERSION" >> $GITHUB_OUTPUT
          echo "OPENSSL_SHA256=$OPENSSL_SHA256" >> $GITHUB_OUTPUT
          echo "NGTCP2_VERSION=$NGTCP2_VERSION" >> $GITHUB_OUTPUT
          echo "NGHTTP3_VERSION=$NGHTTP3_VERSION" >> $GITHUB_OUTPUT
          echo "SFPARSE_VERSION=$SFPARSE_VERSION" >> $GITHUB_OUTPUT
          echo "QUIC_BUILDENV_VERSION=$QUIC_BUILDENV_VERSION" >> $GITHUB_OUTPUT
          echo "QUIC_BUILDENV_BUILD_DATE=$(date -u)" >> $GITHUB_OUTPUT

  build:
    needs: detect_versions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v7
        with:
          platforms: linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          file: ./openssl+quic/Dockerfile
          build-args: |
            BUILDENV_BUILD_DATE=${{ needs.detect_versions.outputs.QUIC_BUILDENV_BUILD_DATE }}
            OPENSSL_VERSION=${{ needs.detect_versions.outputs.OPENSSL_VERSION }}
            OPENSSL_BUILDENV_VERSION=${{ needs.detect_versions.outputs.OPENSSL_BUILDENV_VERSION }}
            OPENSSL_SHA256=${{ needs.detect_versions.outputs.OPENSSL_SHA256 }}
            NGTCP2_VERSION=${{ needs.detect_versions.outputs.NGTCP2_VERSION }}
            NGHTTP3_VERSION=${{ needs.detect_versions.outputs.NGHTTP3_VERSION }}
            SFPARSE_VERSION=${{ needs.detect_versions.outputs.SFPARSE_VERSION }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:${{ needs.detect_versions.outputs.QUIC_BUILDENV_VERSION }}

  finalize:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push manifest
        run: |
          VERSION="${{ needs.detect_versions.outputs.QUIC_BUILDENV_VERSION }}"
          docker manifest push ${{ env.DOCKERHUB_SLUG }}:$VERSION
