name: CD Build OpenSSL QUIC Buildenv

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: openssl
            dockerfile: ./openssl/openssl.Dockerfile
            arch: amd64
            platform: linux/amd64
          - variant: openssl
            dockerfile: ./openssl/openssl.Dockerfile
            arch: 386
            platform: linux/386
          - variant: openssl
            dockerfile: ./openssl/openssl.Dockerfile
            arch: armv6
            platform: linux/arm/v6
          - variant: openssl
            dockerfile: ./openssl/openssl.Dockerfile
            arch: armv7
            platform: linux/arm/v7
          - variant: openssl
            dockerfile: ./openssl/openssl.Dockerfile
            arch: arm64
            platform: linux/arm64
          - variant: openssl
            dockerfile: ./openssl/openssl.Dockerfile
            arch: ppc64le
            platform: linux/ppc64le
          - variant: openssl
            dockerfile: ./openssl/openssl.Dockerfile
            arch: s390x
            platform: linux/s390x
          - variant: openssl
            dockerfile: ./openssl/openssl.Dockerfile
            arch: riscv64
            platform: linux/riscv64

          - variant: openssl+quic
            dockerfile: ./openssl/openssl_quic.Dockerfile
            arch: amd64
            platform: linux/amd64
          - variant: openssl+quic
            dockerfile: ./openssl/openssl_quic.Dockerfile
            arch: 386
            platform: linux/386
          - variant: openssl+quic
            dockerfile: ./openssl/openssl_quic.Dockerfile
            arch: armv6
            platform: linux/arm/v6
          - variant: openssl+quic
            dockerfile: ./openssl/openssl_quic.Dockerfile
            arch: armv7
            platform: linux/arm/v7
          - variant: openssl+quic
            dockerfile: ./openssl/openssl_quic.Dockerfile
            arch: arm64
            platform: linux/arm64
          - variant: openssl+quic
            dockerfile: ./openssl/openssl_quic.Dockerfile
            arch: ppc64le
            platform: linux/ppc64le
          - variant: openssl+quic
            dockerfile: ./openssl/openssl_quic.Dockerfile
            arch: s390x
            platform: linux/s390x
          - variant: openssl+quic
            dockerfile: ./openssl/openssl_quic.Dockerfile
            arch: riscv64
            platform: linux/riscv64

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Load versions
        id: vars
        run: |
          set -euo pipefail

          OPENSSL_VERSION=$(cat versions/openssl.txt)
          NGTCP2_VERSION=$(cat versions/ngtcp2.txt)
          NGHTTP3_VERSION=$(cat versions/nghttp3.txt)

          BASE_VERSION="${OPENSSL_VERSION#openssl-}"

          BRANCH="${GITHUB_REF_NAME}"

          if [[ "$BRANCH" =~ ^openssl-[0-9]+\.[0-9]+\.[0-9]+-(.+)$ ]]; then
            SUFFIX="${BASH_REMATCH[1]}"
          else
            SUFFIX="0"
          fi

          OPENSSL_FINAL="${BASE_VERSION}-${SUFFIX}"
          QUIC_FINAL="${BASE_VERSION}-${SUFFIX}-quic"

          OPENSSL_SHA256=$(curl -sL "https://github.com/openssl/openssl/releases/download/${OPENSSL_VERSION}/${OPENSSL_VERSION}.tar.gz.sha256" | cut -d ' ' -f1)
          BUILDENV_BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "OPENSSL_VERSION=${OPENSSL_VERSION}" >> "$GITHUB_OUTPUT"
          echo "NGTCP2_VERSION=${NGTCP2_VERSION}" >> "$GITHUB_OUTPUT"
          echo "NGHTTP3_VERSION=${NGHTTP3_VERSION}" >> "$GITHUB_OUTPUT"
          echo "OPENSSL_FINAL=${OPENSSL_FINAL}" >> "$GITHUB_OUTPUT"
          echo "QUIC_FINAL=${QUIC_FINAL}" >> "$GITHUB_OUTPUT"
          echo "OPENSSL_SHA256=${OPENSSL_SHA256}" >> "$GITHUB_OUTPUT"
          echo "BUILDENV_BUILD_DATE=${BUILDENV_BUILD_DATE}" >> "$GITHUB_OUTPUT"


      - uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5

      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build OpenSSL
        if: ${{ matrix.variant == 'openssl' }}
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          cache-from: type=registry,ref=madnuttah/openssl-buildenv:buildcache-${{ matrix.arch }}
          cache-to: type=registry,ref=madnuttah/openssl-buildenv:buildcache-${{ matrix.arch }},mode=max
          build-args: |
            BUILDENV_BUILD_DATE=${{ steps.vars.outputs.BUILDENV_BUILD_DATE }}
            OPENSSL_VERSION=${{ steps.vars.outputs.OPENSSL_VERSION }}
            OPENSSL_SHA256=${{ steps.vars.outputs.OPENSSL_SHA256 }}
            TARGETARCH=${{ matrix.arch }}
          tags: |
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-${{ matrix.arch }}

      - name: Build QUIC
        if: ${{ matrix.variant == 'openssl+quic' }}
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          cache-from: type=registry,ref=madnuttah/openssl-buildenv:buildcache-${{ matrix.arch }}-quic
          cache-to: type=registry,ref=madnuttah/openssl-buildenv:buildcache-${{ matrix.arch }}-quic,mode=max
          build-args: |
            BUILDENV_BUILD_DATE=${{ steps.vars.outputs.BUILDENV_BUILD_DATE }}
            OPENSSL_VERSION=${{ steps.vars.outputs.OPENSSL_VERSION }}
            OPENSSL_SHA256=${{ steps.vars.outputs.OPENSSL_SHA256 }}
            NGTCP2_VERSION=${{ steps.vars.outputs.NGTCP2_VERSION }}
            NGHTTP3_VERSION=${{ steps.vars.outputs.NGHTTP3_VERSION }}
            TARGETARCH=${{ matrix.arch }}
          tags: |
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-${{ matrix.arch }}

  manifest:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: main
          fetch-depth: 0

      - name: Load versions
        id: vars
        run: |
          set -euo pipefail
          OPENSSL_VERSION=$(cat versions/openssl.txt)
          BASE_VERSION="${OPENSSL_VERSION#openssl-}"
          OPENSSL_FINAL="${BASE_VERSION}-0"
          QUIC_FINAL="${BASE_VERSION}-0-quic"

          echo "OPENSSL_FINAL=${OPENSSL_FINAL}" >> "$GITHUB_OUTPUT"
          echo "QUIC_FINAL=${QUIC_FINAL}" >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Manifest OpenSSL
        run: |
          docker buildx imagetools create \
            --tag madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }} \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-amd64 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-386 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-armv6 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-armv7 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-arm64 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-ppc64le \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-s390x \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-riscv64

      - name: Manifest QUIC
        run: |
          docker buildx imagetools create \
            --tag madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }} \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-amd64 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-386 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-armv6 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-armv7 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-arm64 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-ppc64le \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-s390x \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-riscv64

      - name: Latest tags
        run: |
          docker buildx imagetools create \
            --tag madnuttah/openssl-buildenv:latest \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-amd64 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-386 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-armv6 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-armv7 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-arm64 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-ppc64le \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-s390x \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.OPENSSL_FINAL }}-riscv64

          docker buildx imagetools create \
            --tag madnuttah/openssl-buildenv:latest-quic \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-amd64 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-386 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-armv6 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-armv7 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-arm64 \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-ppc64le \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-s390x \
            madnuttah/openssl-buildenv:${{ steps.vars.outputs.QUIC_FINAL }}-riscv64
